# ------------------------------
# Stage 1 : build
# ------------------------------
FROM evenzeppa/42env:latest AS builder

WORKDIR /root/ft_irc

COPY . .

RUN mkdir -p deps

RUN cmake -B build && \
		cmake --build build

# ------------------------------
# Stage 2 : runtime minimal
# ------------------------------
FROM evenzeppa/42env:latest AS app

WORKDIR /root/ft_irc

RUN apt-get update && apt-get install -y tini && apt-get clean

COPY --from=builder /root/ft_irc/build/ircserv ./ircserv

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["./ircserv", "6667", "1234"]
